development:
  clients:
    default:
      database: bluezone_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: bluezone_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
